_BASE_: "../Base-TripleBranchRCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_TRIPLE_BRANCH_WHOLE_MASK_HEAD: 
    BRANCH_GUIDANCE: True
    REFINEMENT: False
    CONSIS_LOSS: True
    CONSIS_LOSS_MODE: "MX"
SOLVER:
  STEPS: (1000, 1300)
  MAX_ITER: 1500