_BASE_: "../Base-RCNN-FPN-COCOA_cls.yaml"
MODEL:
  WEIGHTS: "./R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
    VERSION: 3
    ATTENTION_MODE: "attention"    
    GT_AMODAL_WEIGHT: 1.0
    GT_VISIBLE_WEIGHT: 1.0
    AMODAL_FEATURE_MATCHING: (3, 4)     # index, e.g:(0,1,2,3)
    AMODAL_FM_BETA: (0.01, 0.05)
    RECLS_NET:
      NAME: "ReclsConvFCHead"
      MODE: "adaptive"
      GT_WEIGHT: 0.1
      RESCORING: True
    RECON_NET:
      MASK_THS: 0.95
      LOAD_CODEBOOK: False



TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_CtRef_VAR_cocoa_cls_res50_SGD_1x'